#pragma once
#define PBOX_VERSION_MAJOR 0
#define PBOX_VERSION_MINOR 7
#define PBOX_VERSION_PATCH 0

#ifndef PIXELBOX_DEBUG
#define PIXELBOX_DEBUG 1
#endif

#define PBOX_NUMERIC_VERSION 70
#define PBOX_VERSION "0.7.0"
